#ServerPort
server:
  port: 9595

#DataBase
spring:
  datasource:
    url: jdbc:mysql://mysql.jobit.co.kr:13306/job_it?serverTimezone=Asia/Seoul
    username: root
    password: kosta!234
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      
      